//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LjusOchMiljoAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anvandare
    {
        public int ID { get; set; }
        public string Anvandarnamn { get; set; }
        public string LosenordHash { get; set; }
        public string Roll { get; set; }
        public Nullable<int> Raknare { get; set; }
        public Nullable<bool> Laste { get; set; }
    }
}
