//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LjusOchMiljoAB.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Produkter
    {
        public string ID { get; set; }
        public string Namn { get; set; }
        public Nullable<decimal> Pris { get; set; }
        public string Typ { get; set; }
        public string Farg { get; set; }
        public string Bildfilnamn { get; set; }
        public string Ritningsfilnamn { get; set; }
        public string RefID { get; set; }
        public string Beskrivning { get; set; }
        public string Montering { get; set; }
    }
}
